version: '3.8'

services:
  user-service:
    build:
      context: ./Microservices/user-service
    ports:
      - "3000:3000"
    environment:
      PORT: 3000

  product-service:
    build:
      context: ./Microservices/product-service
    ports:
      - "3001:3001"
    environment:
      PORT: 3001

  order-service:
    build:
      context: ./Microservices/order-service
    ports:
      - "3002:3002"
    environment:
      PORT: 3002

  gateway-service:
    build:
      context: ./Microservices/gateway-service
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      USER_SERVICE_URL: http://user-service:3000
      PRODUCT_SERVICE_URL: http://product-service:3001
      ORDER_SERVICE_URL: http://order-service:3002
